import type {
  Resource,
  ResourceAssignment,
  ResourceCreatePayload,
  ResourceUpdatePayload,
  ResourceAssignPayload,
  ResourceReassignPayload,
  ResourceUnassignPayload,
  ResourcesQueryParams,
  PaginatedResources,
} from "./types";

const nowIso = () => new Date().toISOString();

// ─── Resource Data ────────────────────────────────────────────────────────────

let resources: Resource[] = [
  {
    id: "RES-001",
    resource_name: "Toyota Hilux #1",
    resource_code: "VEH-001",
    resource_type: "VEHICLE",
    status: "IN_USE",
    condition: "GOOD",
    description: "Primary campaign utility vehicle for metro operations. Regularly used for field visits and event logistics.",
    specifications: {
      plate_number: "AAA 1234",
      fuel_type: "Diesel",
      mileage_km: 45820,
      seating_capacity: 5,
      color: "White",
    },
    brand: "Toyota",
    model: "Hilux 2024",
    serial_number: "VIN-TH2024-001",
    acquisition_date: "2024-01-15",
    acquisition_cost: 1750000,
    current_value: 1450000,
    warranty_expiry: "2027-01-15",
    latitude: 14.5547,
    longitude: 121.0244,
    last_location_update: "2026-04-09T08:00:00.000Z",
    last_maintenance_date: "2026-02-10",
    next_maintenance_date: "2026-08-10",
    maintenance_notes: null,
    notes: "Assigned to HQ motor pool. Driver: Ernesto Magbanua.",
    tags: ["field-ops", "transport", "metro"],
    current_assignment: {
      id: "ASH-001",
      office_id: "OFF-001",
      office_name: "Kampanya National HQ",
      assigned_at: "2026-01-10T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-10T09:00:00.000Z",
    updated_at: "2026-02-10T14:00:00.000Z",
  },
  {
    id: "RES-002",
    resource_name: "Toyota Hilux #2",
    resource_code: "VEH-002",
    resource_type: "VEHICLE",
    status: "IN_USE",
    condition: "GOOD",
    description: "Field vehicle assigned to Visayas regional operations. Used for inter-island campaign sorties.",
    specifications: {
      plate_number: "CCC 5678",
      fuel_type: "Diesel",
      mileage_km: 38400,
      seating_capacity: 5,
      color: "Silver",
    },
    brand: "Toyota",
    model: "Hilux 2024",
    serial_number: "VIN-TH2024-002",
    acquisition_date: "2024-01-15",
    acquisition_cost: 1750000,
    current_value: 1500000,
    warranty_expiry: "2027-01-15",
    latitude: 10.3157,
    longitude: 123.8854,
    last_location_update: "2026-04-08T14:30:00.000Z",
    last_maintenance_date: "2026-03-05",
    next_maintenance_date: "2026-09-05",
    maintenance_notes: null,
    notes: null,
    tags: ["field-ops", "transport", "visayas"],
    current_assignment: {
      id: "ASH-002",
      office_id: "OFF-004",
      office_name: "Visayas Regional Office",
      assigned_at: "2026-01-15T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-15T09:00:00.000Z",
    updated_at: "2026-03-05T09:00:00.000Z",
  },
  {
    id: "RES-003",
    resource_name: "Mitsubishi L300 Van",
    resource_code: "VEH-003",
    resource_type: "VEHICLE",
    status: "UNDER_MAINTENANCE",
    condition: "FAIR",
    description: "Cargo van used for transporting campaign materials and equipment. Currently undergoing engine overhaul.",
    specifications: {
      plate_number: "BBB 9012",
      fuel_type: "Diesel",
      mileage_km: 112400,
      seating_capacity: 2,
      cargo_capacity_kg: 1000,
      color: "White",
    },
    brand: "Mitsubishi",
    model: "L300 Van 2020",
    serial_number: "VIN-ML2020-003",
    acquisition_date: "2020-06-10",
    acquisition_cost: 900000,
    current_value: 350000,
    warranty_expiry: null,
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: "2026-03-20",
    next_maintenance_date: "2026-04-20",
    maintenance_notes: "Engine overhaul in progress at Mitsubishi service center. ETA: April 20, 2026.",
    notes: "Unassigned while under maintenance.",
    tags: ["transport", "cargo", "materials"],
    current_assignment: null,
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-20T09:00:00.000Z",
    updated_at: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "RES-004",
    resource_name: "Dell Latitude Laptop #1",
    resource_code: "IT-001",
    resource_type: "IT_ASSET",
    status: "IN_USE",
    condition: "EXCELLENT",
    description: "Primary workstation laptop assigned to the HQ operations team for campaign data management.",
    specifications: {
      processor: "Intel Core i7-1365U",
      ram_gb: 16,
      storage_gb: 512,
      os: "Windows 11 Pro",
      display_inch: 14,
    },
    brand: "Dell",
    model: "Latitude 5540",
    serial_number: "DLL-LAT5540-001",
    acquisition_date: "2025-08-01",
    acquisition_cost: 85000,
    current_value: 75000,
    warranty_expiry: "2028-08-01",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: null,
    next_maintenance_date: null,
    maintenance_notes: null,
    notes: "Assigned to Operations Lead. Serial tag affixed.",
    tags: ["it-asset", "workstation", "hq"],
    current_assignment: {
      id: "ASH-003",
      office_id: "OFF-001",
      office_name: "Kampanya National HQ",
      assigned_at: "2026-01-10T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-10T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-005",
    resource_name: "Dell Latitude Laptop #2",
    resource_code: "IT-002",
    resource_type: "IT_ASSET",
    status: "AVAILABLE",
    condition: "NEW",
    description: "Spare laptop ready for deployment to field offices as needed.",
    specifications: {
      processor: "Intel Core i7-1365U",
      ram_gb: 16,
      storage_gb: 512,
      os: "Windows 11 Pro",
      display_inch: 14,
    },
    brand: "Dell",
    model: "Latitude 5540",
    serial_number: "DLL-LAT5540-002",
    acquisition_date: "2026-02-15",
    acquisition_cost: 85000,
    current_value: 85000,
    warranty_expiry: "2029-02-15",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: null,
    next_maintenance_date: null,
    maintenance_notes: null,
    notes: "In storage, ready for deployment.",
    tags: ["it-asset", "workstation", "spare"],
    current_assignment: null,
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-02-15T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-006",
    resource_name: "HP LaserJet Pro Printer",
    resource_code: "IT-003",
    resource_type: "IT_ASSET",
    status: "IN_USE",
    condition: "GOOD",
    description: "High-capacity network laser printer for printing campaign materials and official documents.",
    specifications: {
      print_speed_ppm: 35,
      print_resolution: "1200 x 1200 dpi",
      paper_capacity_sheets: 500,
      connectivity: "Wi-Fi, Ethernet",
      monthly_duty_cycle: 40000,
    },
    brand: "HP",
    model: "LaserJet Pro M428fdn",
    serial_number: "HP-MFP428-006",
    acquisition_date: "2025-10-01",
    acquisition_cost: 32000,
    current_value: 27000,
    warranty_expiry: "2027-10-01",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: "2026-01-15",
    next_maintenance_date: "2026-07-15",
    maintenance_notes: null,
    notes: "Shared printer for field office staff.",
    tags: ["it-asset", "printing", "field"],
    current_assignment: {
      id: "ASH-004",
      office_id: "OFF-002",
      office_name: "North Luzon Field Office",
      assigned_at: "2026-01-12T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-12T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-007",
    resource_name: "Motorola Two-Way Radio Set (10)",
    resource_code: "COM-001",
    resource_type: "COMMUNICATION",
    status: "IN_USE",
    condition: "GOOD",
    description: "Set of 10 handheld two-way radios for field team coordination during events and ground operations.",
    specifications: {
      quantity: 10,
      range_km: 5,
      frequency: "UHF 400-512 MHz",
      battery_life_hours: 12,
      waterproof_rating: "IP54",
    },
    brand: "Motorola",
    model: "CLP1080",
    serial_number: "MOT-CLP1080-SET1",
    acquisition_date: "2025-11-01",
    acquisition_cost: 45000,
    current_value: 38000,
    warranty_expiry: "2027-11-01",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: null,
    next_maintenance_date: null,
    maintenance_notes: null,
    notes: "Assigned to South Luzon branch for field coordination.",
    tags: ["communication", "field-ops", "events"],
    current_assignment: {
      id: "ASH-005",
      office_id: "OFF-003",
      office_name: "South Luzon Branch",
      assigned_at: "2026-01-20T09:00:00.000Z",
      assigned_by: "U-003",
      assigned_by_name: "Eduardo Reyes",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-20T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-008",
    resource_name: "Folding Tables (20)",
    resource_code: "FUR-001",
    resource_type: "FURNITURE",
    status: "AVAILABLE",
    condition: "GOOD",
    description: "Set of 20 standard folding tables for use in campaign events, registration drives, and community assemblies.",
    specifications: {
      quantity: 20,
      dimensions_cm: "183 x 76 x 74",
      material: "Steel frame, plastic top",
      weight_kg: 8.5,
      max_load_kg: 90,
    },
    brand: null,
    model: null,
    serial_number: null,
    acquisition_date: "2025-09-15",
    acquisition_cost: 18000,
    current_value: 15000,
    warranty_expiry: null,
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: null,
    next_maintenance_date: null,
    maintenance_notes: null,
    notes: "Stored in NCR Warehouse, available for event deployment.",
    tags: ["furniture", "events", "field-ops"],
    current_assignment: null,
    data_classification: "internal",
    created_by: "U-002",
    created_at: "2026-01-25T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-009",
    resource_name: "Portable Generator 5KW",
    resource_code: "EQP-001",
    resource_type: "EQUIPMENT",
    status: "RESERVED",
    condition: "EXCELLENT",
    description: "Heavy-duty portable generator for powering campaign events in areas with unreliable grid power. Reserved for Mindanao operations.",
    specifications: {
      power_output_kw: 5,
      fuel_type: "Gasoline",
      runtime_hours_at_50pct: 8,
      noise_level_db: 68,
      weight_kg: 75,
    },
    brand: "Yamaha",
    model: "EF5500FW",
    serial_number: "YAM-EF5500-009",
    acquisition_date: "2025-12-01",
    acquisition_cost: 45000,
    current_value: 43000,
    warranty_expiry: "2027-12-01",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: "2026-03-01",
    next_maintenance_date: "2026-09-01",
    maintenance_notes: null,
    notes: "Reserved for Mindanao election-day operations.",
    tags: ["equipment", "power", "field-ops", "mindanao"],
    current_assignment: {
      id: "ASH-006",
      office_id: "OFF-005",
      office_name: "Mindanao Satellite Office",
      assigned_at: "2026-02-01T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-02-01T09:00:00.000Z",
    updated_at: "2026-03-01T14:00:00.000Z",
  },
  {
    id: "RES-010",
    resource_name: "Sound System Package",
    resource_code: "EQP-002",
    resource_type: "EQUIPMENT",
    status: "IN_USE",
    condition: "FAIR",
    description: "Complete portable sound system including speakers, amplifier, and microphones for rallies and community assemblies.",
    specifications: {
      output_watts: 1000,
      speakers: 2,
      microphones: 4,
      coverage_area_sqm: 2000,
      includes_wireless_mics: true,
    },
    brand: "JBL",
    model: "EON600 Series Package",
    serial_number: "JBL-EON600-PKG-010",
    acquisition_date: "2024-08-20",
    acquisition_cost: 120000,
    current_value: 80000,
    warranty_expiry: "2026-08-20",
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: "2026-01-20",
    next_maintenance_date: "2026-07-20",
    maintenance_notes: "Left speaker has minor crackle at high volumes. Serviceable.",
    notes: "Stored at HQ, deployed for major events.",
    tags: ["equipment", "events", "audio", "hq"],
    current_assignment: {
      id: "ASH-007",
      office_id: "OFF-001",
      office_name: "Kampanya National HQ",
      assigned_at: "2026-01-10T09:00:00.000Z",
      assigned_by: "U-001",
      assigned_by_name: "Jose dela Cruz",
    },
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-01-10T09:00:00.000Z",
    updated_at: "2026-01-20T11:00:00.000Z",
  },
  {
    id: "RES-011",
    resource_name: "Office Supplies Kit",
    resource_code: "SUP-001",
    resource_type: "SUPPLIES",
    status: "AVAILABLE",
    condition: "NEW",
    description: "Bulk office supplies kit (paper, pens, folders, toners) for general campaign office use.",
    specifications: {
      items_included: ["bond paper (5 boxes)", "ballpens (100 pcs)", "folders (50 pcs)", "toner cartridges (4 pcs)"],
      replenishment_cycle: "Quarterly",
    },
    brand: null,
    model: null,
    serial_number: null,
    acquisition_date: "2026-04-01",
    acquisition_cost: 8500,
    current_value: 8500,
    warranty_expiry: null,
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: null,
    next_maintenance_date: null,
    maintenance_notes: null,
    notes: "Q2 2026 office supplies replenishment. Stored at warehouse.",
    tags: ["supplies", "consumables", "admin"],
    current_assignment: null,
    data_classification: "internal",
    created_by: "U-002",
    created_at: "2026-04-01T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: "RES-012",
    resource_name: "Satellite Phone",
    resource_code: "COM-002",
    resource_type: "COMMUNICATION",
    status: "DECOMMISSIONED",
    condition: "POOR",
    description: "Older satellite phone unit. Decommissioned due to end-of-life and high per-minute costs. Replaced by secure mobile app solution.",
    specifications: {
      network: "Iridium",
      model_year: 2018,
      battery_status: "Degraded",
    },
    brand: "Iridium",
    model: "9575 Extreme",
    serial_number: "IRD-9575-012",
    acquisition_date: "2018-03-01",
    acquisition_cost: 65000,
    current_value: 5000,
    warranty_expiry: null,
    latitude: null,
    longitude: null,
    last_location_update: null,
    last_maintenance_date: "2025-06-01",
    next_maintenance_date: null,
    maintenance_notes: "Battery no longer holds charge. Decommissioned April 2026.",
    notes: "For disposal. No longer in service.",
    tags: ["communication", "decommissioned"],
    current_assignment: null,
    data_classification: "internal",
    created_by: "U-001",
    created_at: "2026-04-05T09:00:00.000Z",
    updated_at: "2026-04-05T09:00:00.000Z",
  },
];

// ─── Assignment History ───────────────────────────────────────────────────────

let assignmentHistory: ResourceAssignment[] = [
  // Current active assignments
  {
    id: "ASH-001",
    resource_id: "RES-001",
    resource_name: "Toyota Hilux #1",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2026-01-10T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Initial assignment to HQ motor pool.",
  },
  {
    id: "ASH-002",
    resource_id: "RES-002",
    resource_name: "Toyota Hilux #2",
    office_id: "OFF-004",
    office_name: "Visayas Regional Office",
    assigned_at: "2026-01-15T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Assigned to support Visayas regional field operations.",
  },
  {
    id: "ASH-003",
    resource_id: "RES-004",
    resource_name: "Dell Latitude Laptop #1",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2026-01-10T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Assigned to Operations Lead workstation.",
  },
  {
    id: "ASH-004",
    resource_id: "RES-006",
    resource_name: "HP LaserJet Pro Printer",
    office_id: "OFF-002",
    office_name: "North Luzon Field Office",
    assigned_at: "2026-01-12T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: null,
  },
  {
    id: "ASH-005",
    resource_id: "RES-007",
    resource_name: "Motorola Two-Way Radio Set (10)",
    office_id: "OFF-003",
    office_name: "South Luzon Branch",
    assigned_at: "2026-01-20T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-003",
    assigned_by_name: "Eduardo Reyes",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Assigned for South Luzon field team coordination.",
  },
  {
    id: "ASH-006",
    resource_id: "RES-009",
    resource_name: "Portable Generator 5KW",
    office_id: "OFF-005",
    office_name: "Mindanao Satellite Office",
    assigned_at: "2026-02-01T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Reserved for Mindanao election-day operations.",
  },
  {
    id: "ASH-007",
    resource_id: "RES-010",
    resource_name: "Sound System Package",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2026-01-10T09:00:00.000Z",
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: "Stored at HQ, for major events deployment.",
  },
  // Historical (past) assignments
  {
    id: "ASH-008",
    resource_id: "RES-001",
    resource_name: "Toyota Hilux #1",
    office_id: "OFF-003",
    office_name: "South Luzon Branch",
    assigned_at: "2025-12-01T09:00:00.000Z",
    unassigned_at: "2026-01-09T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Temporary assignment to South Luzon branch for year-end operations.",
  },
  {
    id: "ASH-009",
    resource_id: "RES-003",
    resource_name: "Mitsubishi L300 Van",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2025-11-15T09:00:00.000Z",
    unassigned_at: "2026-03-20T08:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-002",
    unassigned_by_name: "Maria Santos",
    from_office_id: null,
    from_office_name: null,
    notes: "Pulled from HQ for scheduled maintenance.",
  },
  {
    id: "ASH-010",
    resource_id: "RES-007",
    resource_name: "Motorola Two-Way Radio Set (10)",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2025-11-01T09:00:00.000Z",
    unassigned_at: "2026-01-19T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Initial holding at HQ before south Luzon deployment.",
  },
  {
    id: "ASH-011",
    resource_id: "RES-010",
    resource_name: "Sound System Package",
    office_id: "OFF-004",
    office_name: "Visayas Regional Office",
    assigned_at: "2025-12-10T09:00:00.000Z",
    unassigned_at: "2026-01-09T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-004",
    unassigned_by_name: "Ricardo Ramos",
    from_office_id: null,
    from_office_name: null,
    notes: "Deployed to Visayas for regional assembly. Returned to HQ after event.",
  },
  {
    id: "ASH-012",
    resource_id: "RES-002",
    resource_name: "Toyota Hilux #2",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2025-11-05T09:00:00.000Z",
    unassigned_at: "2026-01-14T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Held at HQ pending assignment decision.",
  },
  {
    id: "ASH-013",
    resource_id: "RES-009",
    resource_name: "Portable Generator 5KW",
    office_id: "OFF-006",
    office_name: "NCR Warehouse",
    assigned_at: "2025-12-01T09:00:00.000Z",
    unassigned_at: "2026-01-31T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Staged at warehouse before Mindanao deployment.",
  },
  {
    id: "ASH-014",
    resource_id: "RES-006",
    resource_name: "HP LaserJet Pro Printer",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2025-10-05T09:00:00.000Z",
    unassigned_at: "2026-01-11T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Transferred to North Luzon field office for better utilization.",
  },
  {
    id: "ASH-015",
    resource_id: "RES-012",
    resource_name: "Satellite Phone",
    office_id: "OFF-001",
    office_name: "Kampanya National HQ",
    assigned_at: "2023-06-01T09:00:00.000Z",
    unassigned_at: "2026-04-05T09:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Decommissioned. Returned to pool for disposal.",
  },
  {
    id: "ASH-016",
    resource_id: "RES-004",
    resource_name: "Dell Latitude Laptop #1",
    office_id: "OFF-003",
    office_name: "South Luzon Branch",
    assigned_at: "2025-08-05T09:00:00.000Z",
    unassigned_at: "2026-01-09T17:00:00.000Z",
    assigned_by: "U-001",
    assigned_by_name: "Jose dela Cruz",
    unassigned_by: "U-001",
    unassigned_by_name: "Jose dela Cruz",
    from_office_id: null,
    from_office_name: null,
    notes: "Previously used in South Luzon branch. Transferred back to HQ.",
  },
];

// ─── Helper ───────────────────────────────────────────────────────────────────

function paginateSkipLimit<T>(items: T[], skip = 0, limit = 25): { items: T[]; total: number; skip: number; limit: number } {
  return {
    items: items.slice(skip, skip + limit),
    total: items.length,
    skip,
    limit,
  };
}

// ─── Exported Functions ───────────────────────────────────────────────────────

export function listDemoResources(params: ResourcesQueryParams = {}): PaginatedResources {
  let filtered = resources.filter((r) => {
    if (params.resource_type && r.resource_type !== params.resource_type) return false;
    if (params.status && r.status !== params.status) return false;
    if (params.condition && r.condition !== params.condition) return false;
    if (params.office_id && r.current_assignment?.office_id !== params.office_id) return false;
    if (params.unassigned && r.current_assignment !== null) return false;
    if (params.tag && !r.tags.includes(params.tag)) return false;
    if (params.min_value != null && (r.current_value ?? 0) < params.min_value) return false;
    if (params.max_value != null && (r.current_value ?? 0) > params.max_value) return false;
    if (params.maintenance_due) {
      if (!r.next_maintenance_date) return false;
      const due = new Date(r.next_maintenance_date);
      const now = new Date();
      if (due > now) return false;
    }
    if (params.search) {
      const q = params.search.toLowerCase();
      if (
        !r.resource_name.toLowerCase().includes(q) &&
        !(r.resource_code?.toLowerCase().includes(q)) &&
        !(r.brand?.toLowerCase().includes(q)) &&
        !(r.model?.toLowerCase().includes(q))
      ) return false;
    }
    return true;
  });
  return paginateSkipLimit(filtered, params.skip ?? 0, params.limit ?? 25);
}

export function getDemoResource(id: string): Resource {
  const resource = resources.find((r) => r.id === id);
  if (!resource) throw new Error(`Resource not found: ${id}`);
  return resource;
}

export function createDemoResource(payload: ResourceCreatePayload): { message: string; data: Resource } {
  const newId = `RES-${String(resources.length + 1).padStart(3, "0")}`;
  const created: Resource = {
    id: newId,
    resource_name: payload.resource_name,
    resource_code: payload.resource_code ?? null,
    resource_type: payload.resource_type,
    status: payload.status ?? "AVAILABLE",
    condition: payload.condition ?? "GOOD",
    description: payload.description ?? null,
    specifications: payload.specifications ?? {},
    brand: payload.brand ?? null,
    model: payload.model ?? null,
    serial_number: payload.serial_number ?? null,
    acquisition_date: payload.acquisition_date ?? null,
    acquisition_cost: payload.acquisition_cost ?? null,
    current_value: payload.current_value ?? null,
    warranty_expiry: payload.warranty_expiry ?? null,
    latitude: payload.latitude ?? null,
    longitude: payload.longitude ?? null,
    last_location_update: null,
    last_maintenance_date: payload.last_maintenance_date ?? null,
    next_maintenance_date: payload.next_maintenance_date ?? null,
    maintenance_notes: payload.maintenance_notes ?? null,
    notes: payload.notes ?? null,
    tags: payload.tags ?? [],
    current_assignment: null,
    data_classification: payload.data_classification ?? "internal",
    created_by: "U-001",
    created_at: nowIso(),
    updated_at: null,
  };
  resources = [created, ...resources];
  return { message: "Resource created successfully.", data: created };
}

export function updateDemoResource(id: string, payload: ResourceUpdatePayload): { message: string; data: Resource } {
  const idx = resources.findIndex((r) => r.id === id);
  if (idx < 0) throw new Error(`Resource not found: ${id}`);
  const updated: Resource = { ...resources[idx], ...payload, updated_at: nowIso() };
  resources[idx] = updated;
  return { message: "Resource updated successfully.", data: updated };
}

export function deleteDemoResource(id: string): void {
  const idx = resources.findIndex((r) => r.id === id);
  if (idx < 0) throw new Error(`Resource not found: ${id}`);
  resources[idx] = { ...resources[idx], status: "DISPOSED", current_assignment: null, updated_at: nowIso() };
}

export function assignDemoResource(resourceId: string, payload: ResourceAssignPayload): { message: string; data: ResourceAssignment } {
  const idx = resources.findIndex((r) => r.id === resourceId);
  if (idx < 0) throw new Error(`Resource not found: ${resourceId}`);
  const newId = `ASH-${String(assignmentHistory.length + 1).padStart(3, "0")}`;
  const assignment: ResourceAssignment = {
    id: newId,
    resource_id: resourceId,
    resource_name: resources[idx].resource_name,
    office_id: payload.office_id,
    office_name: `Office ${payload.office_id}`,
    assigned_at: nowIso(),
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Demo User",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: null,
    from_office_name: null,
    notes: payload.notes ?? null,
  };
  assignmentHistory = [assignment, ...assignmentHistory];
  resources[idx] = {
    ...resources[idx],
    status: "IN_USE",
    current_assignment: {
      id: newId,
      office_id: payload.office_id,
      office_name: assignment.office_name,
      assigned_at: assignment.assigned_at,
      assigned_by: "U-001",
      assigned_by_name: "Demo User",
    },
    updated_at: nowIso(),
  };
  return { message: "Resource assigned successfully.", data: assignment };
}

export function unassignDemoResource(resourceId: string, payload: ResourceUnassignPayload = {}): { message: string; data: ResourceAssignment } {
  const idx = resources.findIndex((r) => r.id === resourceId);
  if (idx < 0) throw new Error(`Resource not found: ${resourceId}`);
  const currentAssignment = resources[idx].current_assignment;
  if (!currentAssignment) throw new Error("Resource is not currently assigned.");
  const histIdx = assignmentHistory.findIndex((a) => a.id === currentAssignment.id);
  const now = nowIso();
  if (histIdx >= 0) {
    assignmentHistory[histIdx] = { ...assignmentHistory[histIdx], unassigned_at: now, unassigned_by: "U-001", unassigned_by_name: "Demo User" };
  }
  const updatedAssignment = histIdx >= 0 ? assignmentHistory[histIdx] : {
    ...currentAssignment,
    resource_id: resourceId,
    resource_name: resources[idx].resource_name,
    unassigned_at: now,
    unassigned_by: "U-001",
    unassigned_by_name: "Demo User",
    from_office_id: null,
    from_office_name: null,
    notes: payload.notes ?? null,
  } as ResourceAssignment;
  resources[idx] = { ...resources[idx], status: "AVAILABLE", current_assignment: null, updated_at: now };
  return { message: "Resource unassigned successfully.", data: updatedAssignment };
}

export function reassignDemoResource(resourceId: string, payload: ResourceReassignPayload): { message: string; data: ResourceAssignment } {
  const idx = resources.findIndex((r) => r.id === resourceId);
  if (idx < 0) throw new Error(`Resource not found: ${resourceId}`);
  const now = nowIso();
  const fromAssignment = resources[idx].current_assignment;
  if (fromAssignment) {
    const histIdx = assignmentHistory.findIndex((a) => a.id === fromAssignment.id);
    if (histIdx >= 0) {
      assignmentHistory[histIdx] = { ...assignmentHistory[histIdx], unassigned_at: now, unassigned_by: "U-001", unassigned_by_name: "Demo User" };
    }
  }
  const newId = `ASH-${String(assignmentHistory.length + 1).padStart(3, "0")}`;
  const newAssignment: ResourceAssignment = {
    id: newId,
    resource_id: resourceId,
    resource_name: resources[idx].resource_name,
    office_id: payload.target_office_id,
    office_name: `Office ${payload.target_office_id}`,
    assigned_at: now,
    unassigned_at: null,
    assigned_by: "U-001",
    assigned_by_name: "Demo User",
    unassigned_by: null,
    unassigned_by_name: null,
    from_office_id: fromAssignment?.office_id ?? null,
    from_office_name: fromAssignment?.office_name ?? null,
    notes: payload.notes ?? null,
  };
  assignmentHistory = [newAssignment, ...assignmentHistory];
  resources[idx] = {
    ...resources[idx],
    current_assignment: {
      id: newId,
      office_id: payload.target_office_id,
      office_name: newAssignment.office_name,
      assigned_at: now,
      assigned_by: "U-001",
      assigned_by_name: "Demo User",
    },
    updated_at: now,
  };
  return { message: "Resource reassigned successfully.", data: newAssignment };
}

export function getDemoResourceHistory(resourceId: string): ResourceAssignment[] {
  return assignmentHistory
    .filter((a) => a.resource_id === resourceId)
    .sort((a, b) => new Date(b.assigned_at).getTime() - new Date(a.assigned_at).getTime());
}

export function listDemoOfficeResources(officeId: string): Resource[] {
  return resources.filter((r) => r.current_assignment?.office_id === officeId);
}
